import { describe,it,expect,vi } from "vitest";
import { createOrdinarySharedJournalPort,createDisabledSharedJournalPort } from "./shared-journal-adapter";
import { createJournalPreview,beginJournalAttempt,resolveJournalAttempt,type SharedJournalIntent } from "./shared-journal-contract";
import { createSyntheticJournalHttpHandler } from "./shared-journal-synthetic-http";
import { fixture,ids,id } from "./workflow.test-fixture";
function setup(){const h=fixture(),snapshot=h.snapshot(),identity={actorId:ids.actor,organizationId:ids.org};const selectedScope={propertyId:ids.property,unitId:ids.unit};
 const record=createJournalPreview({scope:{...identity,leaseId:ids.lease},selectedScope,token:id(50),idempotencyKey:id(51),payload:{operation:"apply",leaseId:ids.lease,depositId:ids.deposit,invoiceId:ids.invoice,lineId:ids.line,amount:"100.00",date:"2026-10-04",reason:"Settle rent"},snapshotHash:snapshot.fingerprint,authorizationHash:"a".repeat(64),expiresAt:10000});
 const authority={scope:record.scope,selectedScope,authorizationHash:record.authorizationHash,allowed:true};let current:SharedJournalIntent=record;let error:null|{code:string;message:string}=null;
 const rpc=vi.fn(async(name:string)=>{if(error)return {data:null,error};if(name==="get_local_deposit_rent_candidates")return {data:snapshot,error:null};if(name==="begin_deposit_rent_journal_attempt")current=beginJournalAttempt(current,proof(record),authority,snapshot.fingerprint,1);if(name==="execute_deposit_rent_journal")current=resolveJournalAttempt(current,proof(record),authority,{commandId:id(60),message:"Original confirmed."});return {data:current,error:null};});
 const who=vi.fn(async()=>identity as typeof identity|null),client=vi.fn(async()=>({rpc}));return {record,snapshot,rpc,who,client,port:createOrdinarySharedJournalPort({identity:who,client}),setError:(value:typeof error)=>{error=value;},setRecord:(value:SharedJournalIntent)=>{current=value;}};
}
const proof=(r:SharedJournalIntent)=>({token:r.token,idempotencyKey:r.idempotencyKey,payloadHash:r.payloadHash,revision:r.revision});
const req=(body:unknown,origin="http://127.0.0.1:50123")=>new Request("http://127.0.0.1:50123/journal",{method:"POST",headers:{origin,"Content-Type":"application/json"},body:JSON.stringify(body)});
describe("dormant ordinary shared-journal adapter",()=>{
 it("binds org/actor to server session, verifies candidate and sends canonical payload with DB snapshot",async()=>{const h=setup();expect(await h.port.prepare(h.record.payload)).toEqual(h.record);expect(h.rpc).toHaveBeenLastCalledWith("prepare_deposit_rent_journal",{p_org:ids.org,p_lease:ids.lease,p_payload:h.record.payload,p_expected_snapshot:h.snapshot.fingerprint});});
 it("uses only saved proof for separate durable begin and original execution",async()=>{const h=setup();expect((await h.port.beginAttempt(ids.lease,proof(h.record))).state).toBe("attempted");expect((await h.port.executeOriginal(ids.lease,proof(h.record))).state).toBe("resolved");expect(h.rpc).toHaveBeenLastCalledWith("execute_deposit_rent_journal",{p_org:ids.org,p_lease:ids.lease,p_token:h.record.token,p_key:h.record.idempotencyKey,p_payload_hash:h.record.payloadHash});});
 it("denies absent identity before client creation and maps private backend denial safely",async()=>{const h=setup();h.who.mockResolvedValueOnce(null);await expect(h.port.readCurrent(ids.lease)).rejects.toMatchObject({status:401});expect(h.client).not.toHaveBeenCalled();h.setError({code:"42501",message:"private secret"});await expect(h.port.readCurrent(ids.lease)).rejects.toMatchObject({status:403});});
 it("rejects foreign scope, corrupt payload hash and missing result evidence",async()=>{for(const mutate of [(r:SharedJournalIntent)=>({...r,scope:{...r.scope,actorId:id(99)}}),(r:SharedJournalIntent)=>({...r,payloadHash:"c".repeat(64)}),(r:SharedJournalIntent)=>({...r,state:"resolved" as const})]){const h=setup();h.setRecord(mutate(h.record));await expect(h.port.readCurrent(ids.lease)).rejects.toThrow();}});
 it("keeps production factory disabled",async()=>{await expect(createDisabledSharedJournalPort().readCurrent(ids.lease)).rejects.toThrow("disabled");});
 it("requires loopback same-origin and bounded request with no actor/org override",async()=>{const h=setup(),port=vi.fn(()=>h.port),handler=createSyntheticJournalHttpHandler(port);expect((await handler(req({operation:"read",leaseId:ids.lease},"https://foreign.example"))).status).toBe(403);expect(port).not.toHaveBeenCalled();expect((await handler(req({operation:"read",leaseId:ids.lease,actorId:id(99)}))).status).toBe(400);expect((await handler(req({padding:"x".repeat(17000)}))).status).toBe(413);});
 it("invokes barrier only after actual durable begin and resolved RPC, preserves original retry after dropped response",async()=>{const h=setup(),events:string[]=[];const handler=createSyntheticJournalHttpHandler(()=>h.port,async phase=>{events.push(phase);if(phase==="durable-resolution-before-response")throw Error("drop");});expect((await handler(req({operation:"begin",leaseId:ids.lease,proof:proof(h.record)}))).status).toBe(200);expect((await handler(req({operation:"execute",leaseId:ids.lease,proof:proof(h.record)}))).status).toBe(503);expect(events).toEqual(["durable-attempt","before-dispatch","durable-resolution-before-response"]);const recovered=await h.port.readCurrent(ids.lease);expect(recovered?.state).toBe("resolved");expect(recovered?.idempotencyKey).toBe(h.record.idempotencyKey);});
});
