import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createJournalPreview, replaceJournalPreview, beginJournalAttempt, recoverJournalIntent, resolveJournalAttempt, canonicalJournalPayload, type SharedJournalIntent } from "./shared-journal-contract";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const scope={organizationId:id(1),actorId:id(2),leaseId:id(3)}, selectedScope={propertyId:id(10),unitId:id(11)}, auth={scope,selectedScope,allowed:true,authorizationHash:"a".repeat(64)};
const make=(n=4)=>createJournalPreview({scope,selectedScope,token:id(n),idempotencyKey:id(n+1),payload:{operation:"apply",leaseId:scope.leaseId,depositId:id(6),invoiceId:id(7),lineId:id(8),amount:"100.00",date:"2026-10-04",reason:"Settle rent"},snapshotHash:"b".repeat(64),authorizationHash:auth.authorizationHash,expiresAt:1000});
const proof=(r:SharedJournalIntent)=>({token:r.token,idempotencyKey:r.idempotencyKey,payloadHash:r.payloadHash,revision:r.revision});
const result={commandId:id(99),message:"Original action confirmed."};
// Shared synthetic service, not a database/durability certification. Both
// clients use the same atomic slot; execution commits result+financial count.
function service(initial:SharedJournalIntent){let current=initial,postings=0;const archive:SharedJournalIntent[]=[];let tail=Promise.resolve();const atomic=<T>(fn:()=>T)=>{const task=tail.then(fn);tail=task.then(()=>undefined,()=>undefined);return task;};return {client:()=>({begin:()=>atomic(()=>current=beginJournalAttempt(current,proof(initial),auth,initial.snapshotHash,1)),execute:(loseResponse=false)=>atomic(()=>{if(current.state!=="resolved"){const resolved=resolveJournalAttempt(current,proof(initial),auth,result);postings++;current=resolved;}if(loseResponse)throw Error("Response lost after commit");return recoverJournalIntent(current,proof(initial),auth);}),replace:(next:SharedJournalIntent)=>atomic(()=>{const old=current;current=replaceJournalPreview(current,next,auth);archive.push(old);return current;}),read:()=>atomic(()=>current)}),postings:()=>postings,archive};}
describe("dormant shared journal contract",()=>{
 it("matches independent fixed cross-language canonical text and SHA256 vectors",()=>{const vectors=JSON.parse(readFileSync("scripts/deposit-rent-journal-canonical-vectors.json","utf8"));for(const v of vectors){const actual=canonicalJournalPayload(v.payload);expect(actual.text,v.name).toBe(v.canonicalText);expect(actual.hash,v.name).toBe(v.sha256);}});
 it("rejects nonfresh replacements, result-bearing previews and forged payload evidence",()=>{const original=make(),next=make(20);for(const invalid of [{...next,state:"attempted" as const},{...next,state:"resolved" as const,result},{...next,result},{...next,revision:2},{...next,payloadHash:"c".repeat(64)}])expect(()=>replaceJournalPreview(original,invalid,auth)).toThrow();});
 it("rejects property/unit transfer on attempt, execute and recovery even with unchanged access",()=>{const a=make(),b=beginJournalAttempt(a,proof(a),auth,a.snapshotHash,1);for(const changed of [{propertyId:id(50),unitId:selectedScope.unitId},{...selectedScope,unitId:id(50)}]){const authority={...auth,selectedScope:changed};expect(()=>beginJournalAttempt(a,proof(a),authority,a.snapshotHash,1)).toThrow("access");expect(()=>recoverJournalIntent(b,proof(a),authority)).toThrow("access");expect(()=>resolveJournalAttempt(b,proof(a),authority,result)).toThrow("access");}});
 it("normalizes canonical cents and trims reasons without using object-key order",()=>{const a=make();if(a.payload.operation!=="apply")throw Error("fixture");const one=canonicalJournalPayload(a.payload),two=canonicalJournalPayload({...a.payload,amount:"000100.00",reason:"  Settle rent  "});expect(two).toEqual(one);expect(one.text).toContain('"deposit-rent-journal-payload-v1"');});
 it("copies and freezes immutable scope/payload/key and hashes canonical validated payload",()=>{const a=make();expect(Object.isFrozen(a)).toBe(true);expect(Object.isFrozen(a.payload)).toBe(true);expect(make().payloadHash).toBe(a.payloadHash);expect(()=>Reflect.set(a.payload,"amount","200.00")).not.toThrow();expect(a.payload.operation==="apply"&&a.payload.amount).toBe("100.00");expect(()=>createJournalPreview({...a,payload:{...a.payload,leaseId:id(55)}})).toThrow("lease mismatch");});
 it("rejects key/token/payload/revision conflicts before attempt",()=>{const a=make();for(const changed of [{token:id(55)},{idempotencyKey:id(55)},{payloadHash:"c".repeat(64)},{revision:10}])expect(()=>beginJournalAttempt(a,{...proof(a),...changed},auth,a.snapshotHash,1)).toThrow("conflict");});
 it("expires unused previews but retains original attempted recovery across expiry and changed snapshot",()=>{const a=make();expect(()=>beginJournalAttempt(a,proof(a),auth,a.snapshotHash,1000)).toThrow("expired");const b=beginJournalAttempt(a,proof(a),auth,a.snapshotHash,1);expect(beginJournalAttempt(b,proof(a),auth,"c".repeat(64),100000)).toBe(b);expect(()=>replaceJournalPreview(b,make(20),auth)).toThrow("unconfirmed");expect(recoverJournalIntent(b,proof(a),auth).idempotencyKey).toBe(a.idempotencyKey);});
 it("denies changed actor/access without deleting or modifying original attempt",()=>{const a=make(),b=beginJournalAttempt(a,proof(a),auth,a.snapshotHash,1);for(const authority of [{...auth,allowed:false},{...auth,authorizationHash:"c".repeat(64)},{...auth,scope:{...scope,actorId:id(50)}}])expect(()=>recoverJournalIntent(b,proof(a),authority)).toThrow("access");expect(recoverJournalIntent(b,proof(a),auth)).toBe(b);});
 it("requires attempted state and preserves immutable resolved result",()=>{const a=make();expect(()=>resolveJournalAttempt(a,proof(a),auth,result)).toThrow("durably");const b=beginJournalAttempt(a,proof(a),auth,a.snapshotHash,1),c=resolveJournalAttempt(b,proof(a),auth,result);expect(resolveJournalAttempt(c,proof(a),auth,result)).toBe(c);expect(()=>resolveJournalAttempt(c,proof(a),auth,{...result,commandId:id(98)})).toThrow("conflict");});
 it("recovers a committed unknown response from a newly created client with the original key",async()=>{const db=service(make()),first=db.client();await first.begin();await expect(first.execute(true)).rejects.toThrow("lost");const second=db.client();expect((await second.execute()).result).toEqual(result);expect(db.postings()).toBe(1);});
 it("serializes two instances confirming the same original attempt into one posting",async()=>{const db=service(make()),a=db.client(),b=db.client();await Promise.all([a.begin(),b.begin()]);const out=await Promise.all([a.execute(),b.execute()]);expect(out[0].result).toEqual(out[1].result);expect(db.postings()).toBe(1);});
 it("detects a stale confirmation after two competing unused previews",async()=>{const original=make(),db=service(original),a=db.client(),b=db.client();const replacements=await Promise.all([a.replace(make(20)),b.replace(make(30))]);expect(replacements.map(r=>r.token)).toEqual([id(20),id(30)]);const current=await a.read();expect(()=>beginJournalAttempt(current,proof(replacements[0]),auth,current.snapshotHash,1)).toThrow("conflict");expect(db.postings()).toBe(0);});
 it("retains attempted state after dispatch is never reached",async()=>{const original=make(),db=service(original);await db.client().begin();const recovered=await db.client().read();expect(recovered.state).toBe("attempted");expect(recoverJournalIntent(recovered,proof(original),auth).idempotencyKey).toBe(original.idempotencyKey);expect(db.postings()).toBe(0);await db.client().execute();expect(db.postings()).toBe(1);});
 it("blocks concurrent replacement until resolution and archives resolved evidence",async()=>{const db=service(make()),a=db.client(),b=db.client();await a.begin();await expect(b.replace(make(20))).rejects.toThrow("unconfirmed");expect((await a.read()).state).toBe("attempted");await a.execute();await b.replace(make(20));expect(db.archive).toHaveLength(1);expect(db.archive[0].result).toEqual(result);expect(db.postings()).toBe(1);});
});
