// These expressions are generated by register search builders, never supplied
// directly by a caller. Keep the supported grammar deliberately small.
const SEARCH_URL_BUDGET = 4000;
const BATCH_SIZE = 500;

export function needsBoundedSearch(groups: string[]) {
  return groups.reduce((size, group) => size + encodeURIComponent(group).length + 10, 0) > SEARCH_URL_BUDGET;
}

type Result = { data: unknown; error: unknown; count: number | null };

/** Preserve database scope and ordering, but evaluate oversized search filters
 * over bounded pages. Count every match; never truncate the matching ID list.
 * fetchPage must create a fresh query and append a unique order tie-breaker.
 */
export async function readBoundedSearch<R extends Result>(
  groups: string[],
  fetchPage: (from: number, to: number, filters: string[]) => PromiseLike<R>,
  from: number,
  to: number,
  rows: (result: R) => unknown[] = result => result.data as unknown[] ?? [],
): Promise<R> {
  if (!needsBoundedSearch(groups)) return await fetchPage(from, to, groups);
  const predicates = groups.map(group => splitConditions(group).map(compileCondition));
  const visible: unknown[] = [];
  let count = 0;
  let offset = 0;
  while (true) {
    const result = await fetchPage(offset, offset + BATCH_SIZE - 1, []);
    if (result.error) return result;
    const batch = rows(result);
    for (const row of batch) {
      if (!row || typeof row !== "object" || Array.isArray(row)) throw new Error("Invalid register search row");
      if (!predicates.every(group => group.some(matches => matches(row as Record<string, unknown>)))) continue;
      if (count >= from && count <= to) visible.push(row);
      count++;
    }
    offset += batch.length;
    if (!batch.length || (result.count !== null ? offset >= result.count : batch.length < BATCH_SIZE)) {
      return { ...result, data: visible, count };
    }
  }
}

function splitConditions(value: string) {
  const parts: string[] = [];
  let start = 0, depth = 0, quoted = false, escaped = false;
  for (let index = 0; index < value.length; index++) {
    const char = value[index];
    if (escaped) { escaped = false; continue; }
    if (quoted && char === "\\") { escaped = true; continue; }
    if (char === '"') quoted = !quoted;
    if (quoted) continue;
    if (char === "(") depth++;
    if (char === ")") depth--;
    if (char === "," && depth === 0) { parts.push(value.slice(start, index)); start = index + 1; }
  }
  if (quoted || depth !== 0) throw new Error("Invalid register search expression");
  parts.push(value.slice(start));
  return parts;
}

function scalar(value: string): string {
  return value.startsWith('"') ? JSON.parse(value) as string : value;
}

function compileCondition(expression: string) {
  const match = /^([a-z_]+)\.(in|ilike|eq|not\.is)\.([\s\S]*)$/.exec(expression);
  if (!match) throw new Error("Unsupported register search expression");
  const [, field, operator, value] = match;
  if (operator === "in") {
    if (!value.startsWith("(") || !value.endsWith(")")) throw new Error("Invalid search ID list");
    const values = new Set(splitConditions(value.slice(1, -1)).map(scalar));
    return (row: Record<string, unknown>) => row[field] != null && values.has(String(row[field]));
  }
  if (operator === "not.is" && value === "null") return (row: Record<string, unknown>) => row[field] != null;
  if (operator === "eq") return (row: Record<string, unknown>) => row[field] != null && String(row[field]) === scalar(value);
  if (operator !== "ilike") throw new Error("Unsupported register search operator");
  let pattern = "", escaped = false;
  for (const char of scalar(value)) {
    if (!escaped && char === "\\") { escaped = true; continue; }
    pattern += !escaped && (char === "%" || char === "*") ? ".*" : !escaped && char === "_" ? "." : char.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    escaped = false;
  }
  if (escaped) pattern += "\\\\";
  const regex = new RegExp(`^${pattern}$`, "isu");
  return (row: Record<string, unknown>) => row[field] != null && regex.test(String(row[field]));
}
